In [2]:
import numpy as np

In [7]:
# create an array manually
p = np.array([48.858598, 2.294495])
print(p)
# getting dimension of array p
print('dimension ', p.ndim) 
# getting size of each array dimension
print('shape ', p.shape)
# getting dimension length of array p
print('length ', len(p)) 
# getting data type of array p
print('data type ', p.dtype)

[ 48.858598   2.294495]
dimension  1
shape  (2,)
length  2
data type  float64


In [10]:
#reference for data types https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html

# convert data type
a = p.astype(np.float32)
print(a.dtype)

float32


### Array creation

In [32]:
# empty- Create a new array of the given shape and type, without `initializing elements
print(np.empty([3,2], dtype=np.float64))

# empty_like - Array of uninitialized (arbitrary) data with the same shape and type as a.
a = np.array([[1, 2], [4, 3]])
b = np.empty_like(a)
print(np.empty_like(a))

# eye, identity - Create a NxN identity matrix with ones on the diagonal and zero elsewhere
print(np.eye(2, dtype=np.int))
print(np.identity(2, dtype=np.int))

# ones, ones_like - Create a new array with the given shape and type, filled with 1s for all elements
print(np.ones(5))
print(np.ones(4, dtype=np.int))
x = np.array([[0,1,2], [3,4,5]])
print(np.ones_like(x))

# zeros, zeros_like - This is similar to ones, ones_like, but initializing elements with 0s instead
np.zeros(5)
np.zeros(4, dtype=np.int)
x = np.array([[0, 1, 2], [3, 4, 5]])
np.zeros_like(x)

# arange - Create an array with even spaced values in a given intervalnp.arange(2, 5)
np.arange(4, 12, 5)

# full, full_like - Create a new array with the given shape and type, filled with a selected value
np.full((2,2), 3, dtype=np.int)
x = np.ones(3)
np.full_like(x, 2)

# array - Create an array from the existing data
np.array([[1.1, 2.2, 3.3], [4.4, 5.5, 6.6]])

# asarray Convert the input to an array
a = [3.14, 2.46]
np.asarray(a)

# copy - Return an array copy of the given object
a = np.array([[1, 2], [3, 4]])
np.copy(a)

# fromstring Create 1-D array from a string or text
np.fromstring('3.14 2.17', dtype=np.float, sep=' ')

[[ 1.1  2.2]
 [ 3.3  4.4]
 [ 5.5  6.6]]
[[1 2]
 [3 4]]
[[1 0]
 [0 1]]
[[1 0]
 [0 1]]
[ 1.  1.  1.  1.  1.]
[1 1 1 1]
[[1 1 1]
 [1 1 1]]


array([ 3.14,  2.17])

### Indexing and slicing

### Fancy indexing
Besides indexing with slices, NumPy also supports indexing with Boolean or integer
arrays (masks). This method is called fancy indexing. It creates copies, not views.

In [34]:
# First, we take a look at an example of indexing with a Boolean mask array:
a = np.array([3, 5, 1, 10])
b = (a % 5 == 0)
print(b)
c = np.array([[0, 1], [2, 3], [4, 5], [6, 7]])
print(c[b])

[False  True False  True]
[[2 3]
 [6 7]]


In [37]:
# The second example is an illustration of using integer masks on arrays:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(a[[2, 1]])
print(a[[-2, -1]]) # select rows from the end
print(a[[2, 3], [0, 1]]) # take elements at (2, 0) and (3, 1)


[[ 9 10 11 12]
 [ 5  6  7  8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[ 9 14]


### Numerical operations on arrays

In [38]:
# Scalar operations will propagate the value to each element of the array:
a = np.ones(4)
print(a * 2)
print(a + 3)

[ 2.  2.  2.  2.]
[ 4.  4.  4.  4.]


In [39]:
# All arithmetic operations between arrays apply the operation element wise:
a = np.ones([2, 4])
print(a * a)
print(a + a)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 2.  2.  2.  2.]
 [ 2.  2.  2.  2.]]


In [42]:
# Also, here are some examples of comparisons and logical operations:
a = np.array([1, 2, 3, 4])
b = np.array([1, 1, 5, 3])
print(a == b)
print(np.array_equal(a, b)) # array-wise comparison
c = np.array([1, 0])
d = np.array([1, 1])
print(np.logical_and(c, d)) # logical operations

[ True False False False]
False
[ True False]


### Array functions


In [56]:
a = np.array([[0, 5, 10], [20, 25, 30]])
# reshape
a.reshape(3, 2)
# transpose
a.T
#swapaxes - method that takes a pair of axis numbers and returns a view on the data, 
# without making a copy:
a = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
print('swapaxes', a.swapaxes(1, 2))
print('a', a)
# The transposing function is used to do matrix computations; for example, computing
# the inner matrix product XT.X using np.dot:
a = np.array([[1, 2, 3],[4,5,6]])
print(a.T)
np.dot(a.T, a)

swapaxes [[[ 0  3]
  [ 1  4]
  [ 2  5]]

 [[ 6  9]
  [ 7 10]
  [ 8 11]]]
a [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[1 4]
 [2 5]
 [3 6]]


array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [62]:
# sorting
a = np.array ([[6, 34, 1, 6], [0, 5, 2, -1]])
print(np.sort(a)) # sort along the last axis
print(' sort along the first axis', np.sort(a, axis=0)) # sort along the first axis (vertical..)

b = np.argsort(a) # fancy indexing of sorted array
print('b', b)
np.argmax(a) # get index of maximum element

[[ 1  6  6 34]
 [-1  0  2  5]]
 sort along the first axis [[ 0  5  1 -1]
 [ 6 34  2  6]]
b [[2 0 3 1]
 [3 0 2 1]]


1

In [ ]:
# sin, cos, tan, cosh, sinh, tanh, arcos, arctan, deg2rad
# - Trigonometric and hyperbolic functions

# around, round, rint, fix, floor, ceil, trunc 
# - Rounding elements of an array to the given or nearest number

# sqrt, square, exp, expm1, exp2, log, log10, log1p, logaddexp
# - Computing the exponents and logarithms of an array

# add, negative, multiply, devide, power, substract, mod, modf, remainder
# - Set of arithmetic functions on arrays

# greater, greater_equal, less, less_equal, equal, not_equal
# - Perform elementwise comparison: >, >=, <, <=, ==, !=

### Data processing using arrays

In [66]:
# sum - Calculate the sum of all the elements in an array or along the axis
a = np.array([[2,4], [3,5]])
np.sum(a, axis=0)

# prod - Compute the product of array elements over the given axis
np.prod(a, axis=1)

# diff - Calculate the discrete difference along the given axis
np.diff(a, axis=0)

# gradient - Return the gradient of an array
np.gradient(a)

# cross - Return the cross product of two arrays
b = np.array([[1,2], [3,4]])
print(a)
np.cross(a,b)

# var

# std

# mean

# where

# unique

# intersect1d

[[2 4]
 [3 5]]


array([ 0, -3])

### Loading and saving data

### Linear algebra with NumPy

### NumPy random numbers

In [67]:
np.random.seed(20)
# An array of random numbers in the [0.0, 1.0] interval can be generated as follows:
np.random.rand(5)
np.random.rand(5)

np.random.seed(20) # reset seed number
np.random.rand(5)

# If we want to generate random integers in the half-open interval [min, max],
# we can user the randint(min, max, length) function:
np.random.randint(10, 20, 5)

# NumPy also provides for many other distributions, including the Beta,
# bionomial, chi-square, Dirichlet, exponential, F, Gamma, geometric, or Gumbel

array([17, 12, 10, 16, 18])